// build.rs
// =========
// Build script for D-code: Embeds Python engine code into the Rust binary.
//
// This script:
// 1. Collects all Python files from the `engine/` directory
// 2. Optionally obfuscates/encrypts them
// 3. Generates a Rust source file with the embedded code
// 4. Configures Tauri build

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

/// Collect all Python files from a directory recursively
fn collect_python_files(dir: &Path, files: &mut Vec<(String, String)>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // Skip __pycache__ and other hidden directories
                if let Some(name) = path.file_name() {
                    let name_str = name.to_string_lossy();
                    if !name_str.starts_with('.') && !name_str.starts_with('_') {
                        collect_python_files(&path, files);
                    }
                }
            } else if let Some(ext) = path.extension() {
                if ext == "py" {
                    if let Ok(content) = fs::read_to_string(&path) {
                        // Get relative path from engine directory
                        let relative = path
                            .strip_prefix("engine")
                            .unwrap_or(&path)
                            .to_string_lossy()
                            .replace('\\', "/");
                        files.push((relative, content));
                    }
                }
            }
        }
    }
}

/// Simple XOR obfuscation (can be replaced with AES for production)
fn obfuscate(data: &[u8], key: &[u8]) -> Vec<u8> {
    data.iter()
        .enumerate()
        .map(|(i, byte)| byte ^ key[i % key.len()])
        .collect()
}

/// Generate the embedded Python module
fn generate_embedded_python() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("embedded_python.rs");
    
    let mut files: Vec<(String, String)> = Vec::new();
    
    // Collect Python files from engine directory
    let engine_dir = Path::new("engine");
    if engine_dir.exists() {
        collect_python_files(engine_dir, &mut files);
    }
    
    // Generate obfuscation key (in production, use a secure random key)
    let key: [u8; 32] = [
        0x44, 0x2D, 0x43, 0x4F, 0x44, 0x45, 0x2D, 0x53, 
        0x45, 0x43, 0x52, 0x45, 0x54, 0x2D, 0x4B, 0x45,
        0x59, 0x2D, 0x32, 0x30, 0x32, 0x35, 0x2D, 0x56,
        0x31, 0x2E, 0x30, 0x2E, 0x30, 0x21, 0x21, 0x21,
    ];
    
    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs - DO NOT EDIT\n");
    output.push_str("// Contains embedded Python engine code\n\n");
    
    // Write the obfuscation key
    output.push_str("pub const OBFUSCATION_KEY: [u8; 32] = [\n    ");
    for (i, byte) in key.iter().enumerate() {
        output.push_str(&format!("0x{:02X}, ", byte));
        if (i + 1) % 8 == 0 && i < 31 {
            output.push_str("\n    ");
        }
    }
    output.push_str("\n];\n\n");
    
    // Embed each Python file
    output.push_str("/// Embedded Python files (filename, obfuscated_content)\n");
    output.push_str("pub const EMBEDDED_PYTHON_FILES: &[(&str, &[u8])] = &[\n");
    
    for (name, content) in &files {
        let obfuscated = obfuscate(content.as_bytes(), &key);
        output.push_str(&format!("    (\"{}\", &[\n        ", name));
        
        for (i, byte) in obfuscated.iter().enumerate() {
            output.push_str(&format!("0x{:02X}, ", byte));
            if (i + 1) % 16 == 0 {
                output.push_str("\n        ");
            }
        }
        output.push_str("\n    ]),\n");
    }
    
    output.push_str("];\n\n");
    
    // Helper function to deobfuscate
    output.push_str(r#"
/// Deobfuscate embedded Python code
pub fn deobfuscate(data: &[u8]) -> Vec<u8> {
    data.iter()
        .enumerate()
        .map(|(i, byte)| byte ^ OBFUSCATION_KEY[i % OBFUSCATION_KEY.len()])
        .collect()
}

/// Get Python code by filename
pub fn get_python_code(name: &str) -> Option<String> {
    EMBEDDED_PYTHON_FILES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, data)| {
            let deobfuscated = deobfuscate(data);
            String::from_utf8_lossy(&deobfuscated).to_string()
        })
}

/// Get all embedded Python module names
pub fn get_module_names() -> Vec<&'static str> {
    EMBEDDED_PYTHON_FILES
        .iter()
        .map(|(name, _)| *name)
        .collect()
}
"#);
    
    // Write the output file
    let mut file = fs::File::create(&dest_path).expect("Failed to create embedded_python.rs");
    file.write_all(output.as_bytes()).expect("Failed to write embedded_python.rs");
    
    println!("cargo:rerun-if-changed=engine/");
    println!("cargo:rerun-if-changed=build.rs");
    
    // Report embedded files
    println!("cargo:warning=Embedded {} Python files", files.len());
    for (name, _) in &files {
        println!("cargo:warning=  - {}", name);
    }
}

fn main() {
    // Generate embedded Python code
    generate_embedded_python();
}
