"""
planner.py
==========
Planner Agent: Uses Gemini 2.5 Flash to decompose requirements into tasks.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

# Import configuration
try:
    from .config import get_ai_config, create_genai_client
    CONFIG_AVAILABLE = True
except ImportError:
    CONFIG_AVAILABLE = False

# Conditional imports
try:
    from google import genai
    GENAI_AVAILABLE = True
except ImportError:
    genai = None
    GENAI_AVAILABLE = False


@dataclass
class Task:
    """Individual task in the plan."""
    id: str = ""
    title: str = ""
    description: str = ""
    type: str = "code"
    priority: int = 5
    estimated_minutes: int = 15
    dependencies: list = field(default_factory=list)
    files_to_create: list = field(default_factory=list)
    files_to_modify: list = field(default_factory=list)
    status: str = "pending"
    assigned_worker: Optional[str] = None
    
    def model_dump(self):
        return self.__dict__.copy()
    
    @classmethod
    def model_validate(cls, data):
        return cls(**data)


@dataclass
class TaskPlan:
    """Complete task plan generated by the Planner."""
    project_name: str = ""
    project_description: str = ""
    total_tasks: int = 0
    estimated_total_minutes: int = 0
    tasks: list = field(default_factory=list)
    parallel_groups: list = field(default_factory=list)
    
    def model_dump(self):
        return self.__dict__.copy()


@dataclass
class Planner:
    """Planner agent using Gemini 2.5 Flash."""
    api_key: str = field(default_factory=lambda: os.getenv("GEMINI_API_KEY", ""))
    model_name: str = field(default_factory=lambda: os.getenv("DCODE_PLANNER_MODEL", "gemini-2.5-flash-preview-05-20"))
    max_tasks_per_plan: int = 50
    
    _client: Any = field(default=None, init=False)
    _on_stream: Optional[Callable[[str, str], None]] = field(default=None, init=False)
    
    def __post_init__(self) -> None:
        if self.api_key and GENAI_AVAILABLE:
            if CONFIG_AVAILABLE:
                config = get_ai_config()
                self.model_name = config.planner_model
                self._client = create_genai_client()
            elif genai is not None:
                self._client = genai.Client(api_key=self.api_key)
    
    def set_stream_callback(self, callback: Callable[[str, str], None]) -> None:
        self._on_stream = callback
    
    def _emit(self, message: str) -> None:
        if self._on_stream:
            self._on_stream("planner", message)
    
    async def generate_plan(
        self,
        requirements: str,
        existing_files: Optional[list[str]] = None,
        context: Optional[str] = None
    ) -> TaskPlan:
        """Generate a task plan from requirements."""
        if not self._client:
            self._emit("⚠️ No API client configured")
            return TaskPlan(
                project_name="Unknown",
                project_description=requirements[:100],
                total_tasks=0,
                estimated_total_minutes=0,
                tasks=[],
                parallel_groups=[]
            )
        
        self._emit("📋 Analyzing requirements...")
        
        prompt = f"""Analyze requirements and create a task plan as JSON.
Requirements: {requirements}
Existing files: {existing_files or []}
Context: {context or 'None'}

Output format:
{{"project_name": "...", "project_description": "...", "total_tasks": N, 
"estimated_total_minutes": N, "tasks": [...], "parallel_groups": [[...], ...]}}"""

        try:
            response = self._client.models.generate_content(
                model=self.model_name,
                contents=prompt
            )
            
            response_text = response.text.strip()
            if response_text.startswith("```"):
                lines = response_text.split("\n")
                response_text = "\n".join(lines[1:-1])
            
            plan_data = json.loads(response_text)
            tasks = [Task.model_validate(t) for t in plan_data.get("tasks", [])]
            
            return TaskPlan(
                project_name=plan_data.get("project_name", "Unknown"),
                project_description=plan_data.get("project_description", ""),
                total_tasks=plan_data.get("total_tasks", len(tasks)),
                estimated_total_minutes=plan_data.get("estimated_total_minutes", 0),
                tasks=tasks,
                parallel_groups=plan_data.get("parallel_groups", [])
            )
        except Exception as e:
            self._emit(f"❌ Error: {e}")
            return TaskPlan(project_name="Error", project_description=str(e))
    
    def prioritize_tasks(self, tasks: list) -> list:
        """Sort tasks by priority and dependencies."""
        task_map = {t.id: t for t in tasks}
        visited = set()
        result = []
        
        def visit(task_id: str) -> None:
            if task_id in visited or task_id not in task_map:
                return
            visited.add(task_id)
            task = task_map[task_id]
            for dep in task.dependencies:
                visit(dep)
            result.append(task)
        
        for task in sorted(tasks, key=lambda t: -t.priority):
            visit(task.id)
        
        return result
    
    def get_parallel_batch(self, tasks: list, completed: set) -> list:
        """Get tasks that can run in parallel."""
        batch = []
        for task in tasks:
            if task.status != "pending":
                continue
            if all(dep in completed for dep in task.dependencies):
                batch.append(task)
        return batch
